#cloud-config
package_update: true
package_upgrade: true
packages:
  - openjdk-17-jdk
  - git
  - curl
runcmd:
  - curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  - echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y jenkins
  - sudo systemctl enable jenkins
  - sudo systemctl start jenkins
